name: Release

on:
#  pull_request:
#    branches:
#      - "main"
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/soisolutions-corp/appliance-runtime
          tags: |
            type=ref,event=tag

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RELEASE=${{ github.ref_name }}

      - name: Generate netboot assets
        uses: docker/build-push-action@v5
        with:
          context: .
          file: netboot.Dockerfile
          platforms: linux/amd64,linux/arm64
          outputs: type=local,dest=output
          build-args: |
            APPLIANCE_RUNTIME_VERSION=${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          files: output/*/build/**
